Port cpp ta rc1
eclipse-uprotocol/up-tck pull request #90
Opened 2024-07-28 20:05 UTC by agosh01

2024-07-29 18:08 UTC, agosh01 commented on test_agent/cpp/CMakeLists.txt
> +# find_package(up-client-zenoh-cpp REQUIRED)
Add TODO for zenoh

2024-07-31 17:48 UTC, matthewd0123 reviewed
Honestly only one thing I found... not the best guy for reviewing C++ but it all looks good from me. Feature files are looking great

2024-07-31 17:48 UTC, matthewd0123 commented on test_agent/cpp/include/utils.h
> +#ifndef UTILS_H
Add license to this file?

2024-07-31 19:01 UTC, matthewd0123 approved these changes
LGTM

2024-08-06 19:18 UTC, billpittman requested changes
Only a few comments/questions.

2024-08-13 17:43 UTC, gregmedd approved these changes

2024-08-13 17:46 UTC, agosh01 commented on test_manager/reports/summary/summary.json
Let address this after this PR. Diff is not acting as intended even its in gitignore list

2024-08-13 17:48 UTC, billpittman approved these changes

2024-08-13 18:11 UTC, merged